# -*- coding: utf-8 -*-
"""wecode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pDsGt7VwJKnwX1_7Su9uC9T02SzR86uI
"""

def MergeArr(arr1,arr2,a,b):
  arr3=[None]*(a+b)
  i=0
  j=0
  k=0
  while (i<a and j<b):
    if (arr1[i]<arr2[j]):
      arr3[k]=arr1[i]
      k+=1
      i+=1
    else:
      arr3[k]=arr2[j]
      k+=1
      j+=1
  while (i<a):
    arr3[k]=arr1[i]
    k+=1
    i+=1
  while (j<b):
    arr3[k]=arr2[j]
    k+=1
    j+=1
  for i in range (k):
    print (str(arr3[i]),end=" ")
a,b= [int(a) for a in input().split()]
arr1=[]
arr2=[]
x=list(map(int,input().split()))
for i in range (a):
  arr1.append(x[i])
y=list(map(int,input().split()))
for j in range (b):
  arr2.append(y[j])
MergeArr(arr1,arr2,a,b)